export const dummy = {
  dates: {
    maximum: "2024-09-25",
    minimum: "2024-08-14",
  },
  page: 1,
  results: [
    {
      adult: false,
      backdrop_path: "/cgKZtNSETjXJPkAQ4rasV7dnyQH.jpg",
      genre_ids: [27, 35, 14],
      id: 917496,
      original_language: "en",
      original_title: "Beetlejuice Beetlejuice",
      overview:
        "유령과 대화하는 영매로 유명세를 타게 된 리디아와 그런 엄마가 마음에 들지 않는 10대 딸 아스트리드. 할아버지 찰스의 갑작스러운 죽음으로 가족들은 함께 시골 마을에 내려간다. 유령을 보는 엄마가 마음에 들지 않는 아스트리드는 방황하던 중 함정에 빠져 저세상에 발을 들이게 되고 딸을 구하기 위해 리디아는 인간을 믿지 않는 저세상 슈퍼스타 비틀쥬스를 소환한다. 이루지 못한 리디아와의 결혼을 조건으로 내민 비틀쥬스. 이번엔 아스트리드가 비틀쥬스를 다시 저세상으로 보내야 하는데···",
      popularity: 1063.123,
      poster_path: "/ypWQatJYyESE5PIzdlSdiOyWYja.jpg",
      release_date: "2024-09-04",
      title: "비틀쥬스 비틀쥬스",
      video: false,
      vote_average: 7.119,
      vote_count: 655,
    },
    {
      adult: false,
      backdrop_path: "/7aPrv2HFssWcOtpig5G3HEVk3uS.jpg",
      genre_ids: [28, 12, 53],
      id: 718821,
      original_language: "en",
      original_title: "Twisters",
      overview:
        "뉴욕 기상청 직원 케이트는 대학 시절 토네이도에 맞서다 소중한 사람들을 잃고 죄책감에 살고 있다. 그런 그녀 앞에 옛 친구 하비가 찾아와 토네이도를 소멸시킬 수 있는 획기적인 방법을 제안한다.  고민 끝에 합류하게 된 케이트는 하비와 오클라호마로 향하고, 일명 토네이도 카우보이라 불리는 유명 인플루언서 타일러를 만난다. 마치 자연을 정복한 듯이 자신감 넘치는 타일러와 매사 부딪히게 되는 케이트. 어느 날, 모든 것을 집어삼킬 거대한 토네이도가 휘몰아칠 것을 감지하게 되는데…",
      popularity: 591.888,
      poster_path: "/w5mXdM9AIf7urUtoUVYjABdp3g8.jpg",
      release_date: "2024-08-14",
      title: "트위스터스",
      video: false,
      vote_average: 6.987,
      vote_count: 1440,
    },
    {
      adult: false,
      backdrop_path: "/tAwfoDyKiYa4KQdUp3DTMrEs4En.jpg",
      genre_ids: [16, 878, 12, 10751],
      id: 698687,
      original_language: "en",
      original_title: "Transformers One",
      overview:
        "트랜스포머 시리즈의 주역, 옵티머스 프라임과 메가트론이 한때 형제와도 같은 친구사이였고, 그들이 어떻게 사이버트론 행성의 운명을 바꾸고 영원한 숙적이 되었는지 그 시작에 대한 이야기를 다루고 있다.",
      popularity: 750.287,
      poster_path: "/c2JXlWzvXegSda8qaATr8I47kMx.jpg",
      release_date: "2024-09-25",
      title: "트랜스포머 ONE",
      video: false,
      vote_average: 7.5,
      vote_count: 37,
    },
    {
      adult: false,
      backdrop_path: "/m6GbPD59FZlwqb1vH3exXBsHB6r.jpg",
      genre_ids: [10749, 18],
      id: 1079091,
      original_language: "en",
      original_title: "It Ends with Us",
      overview:
        "아버지의 장례식을 멋지게 망치고 아지트로 향한 ‘릴리’는 어딘가 위태롭지만 매력적인 남자 ‘라일’에게 순식간에 마음을 빼앗긴다. 새로운 도시에서 자신의 이름을 건 꽃집을 오픈한 릴리는 운명처럼 라일을 다시 만나게 되고 걷잡을 수 없는 사랑에 빠져든다. 그러던 어느 날, 어린 시절의 모든 상처를 알고 있는 첫사랑 ‘아틀라스’와 우연히 재회한 후 감당하기 벅찬 라일의 위협적인 모습을 목격하게 되고 완벽했던 관계가 순식간에 요동치면서 릴리는 피할 수 없는 선택의 기로에 서게 되는데… 외면하고 싶지만 마주해야 하는 사랑과 선택의 순간 올가을, 모두에게 위로와 용기를 선사하는 특별한 이야기!",
      popularity: 1076.292,
      poster_path: "/287MYoxjfINSyfaaV636Z2ioR36.jpg",
      release_date: "2024-09-13",
      title: "우리가 끝이야",
      video: false,
      vote_average: 6.753,
      vote_count: 340,
    },
    {
      adult: false,
      backdrop_path: "/9SSEUrSqhljBMzRe4aBTh17rUaC.jpg",
      genre_ids: [27, 878, 28],
      id: 945961,
      original_language: "en",
      original_title: "Alien: Romulus",
      overview:
        "2142년, 부모 세대가 맞닥뜨렸던 암울한 미래를 피하려는 청년들이 더 나은 삶을 찾기 위해 식민지를 떠날 계획을 세운다. 하지만 버려진 우주 기지 로물루스에 도착한 이들은 악몽과도 같은 에이리언의 무자비한 공격에 쫓기기 시작한다. 그 누구도 그들의 절규를 들을 수 없는 우주 한가운데, 생존을 위한 치열한 사투를 벌여야 하는데...",
      popularity: 611.892,
      poster_path: "/bMGcJVd4hXlDcevRJZBK5qROlyP.jpg",
      release_date: "2024-08-14",
      title: "에이리언: 로물루스",
      video: false,
      vote_average: 7.087,
      vote_count: 1049,
    },
    {
      adult: false,
      backdrop_path: "/okVLmXL5y18dfN2R4ufMZEGaeCd.jpg",
      genre_ids: [28, 80, 53, 18],
      id: 1160018,
      original_language: "hi",
      original_title: "किल",
      overview:
        "질주하는 야간열차에 잠입한 무장 강도 집단.열차 승객들을 구하기 위해 나선 특수 요원. 문, 커튼, 손잡이. 손에 잡히는 모든 것이 무기가 된다!  40명의 빌런, 52개의 무기, 9번의 위기! 용서도, 자비도 없다! 짜릿하고 무자비한 복수가 시작된다!",
      popularity: 555.095,
      poster_path: "/hJxdfkQVSzM67uKjInnZA2mJTua.jpg",
      release_date: "2024-08-28",
      title: "킬",
      video: false,
      vote_average: 7.038,
      vote_count: 172,
    },
    {
      adult: false,
      backdrop_path: "/jnrLpUtOKelKhmGieEBcAvrsrFB.jpg",
      genre_ids: [27, 53],
      id: 1114513,
      original_language: "en",
      original_title: "Speak No Evil",
      overview:
        "휴양지에서 처음 만나 우연히 함께 휴가를 보내게 된 두 가족. 패트릭(제임스 맥어보이)은 자신의 집으로 루이스(맥켄지 데이비스)의 가족을 초대한다. 다시 만나 즐거운 시간을 보낼 것이라 예상한 것도 잠시, 거절할 수 없는 호의와 불편한 상황들이 계속되며 불길한 두려움을 느끼고 집에 돌아가려 하던 중 숨겨진 진실을 마주하게 되는데…",
      popularity: 391.959,
      poster_path: "/mXGlp8K10JhiY5ZNY7zMldm2lss.jpg",
      release_date: "2024-09-11",
      title: "스픽 노 이블",
      video: false,
      vote_average: 6.953,
      vote_count: 171,
    },
    {
      adult: false,
      backdrop_path: "/p5kpFS0P3lIwzwzHBOULQovNWyj.jpg",
      genre_ids: [53, 80, 27],
      id: 1032823,
      original_language: "en",
      original_title: "Trap",
      overview:
        "10대 딸과 함께 인기 팝스타의 콘서트를 찾은 쿠퍼. 신나게 콘서트를 즐기던 그는 순간 이상한 낌새를 느끼고, 그곳이 최악의 연쇄살인마를 잡기 위한 거대한 덫임을 알게 된다. 그런데 문제는 쿠퍼 자신이 바로 연쇄살인마라는 것! 이제 쿠퍼는 수많은 관객과 경찰을 따돌리고 어린 딸과 함께 무사히 이 덫에서 탈출해야만 하는데…",
      popularity: 376.286,
      poster_path: "/2LC4gLNbHpZTq28EWOwCMiVnGcq.jpg",
      release_date: "2024-09-18",
      title: "트랩",
      video: false,
      vote_average: 6.524,
      vote_count: 1156,
    },
    {
      adult: false,
      backdrop_path: "/7ks7A3mAO7twDOvBVE4cR8LaIM8.jpg",
      genre_ids: [16, 28, 18],
      id: 1104844,
      original_language: "ja",
      original_title: "劇場版ブルーロック -EPISODE 凪-",
      overview:
        "“귀찮아”가 말버릇인 고등학교 2학년, ‘나기 세이시로’는 하루하루를 무기력하게 살고 있었다. 축구로 전 세계 제패를 꿈꾸는 동급생 ‘미카게 레오’가 그의 재능을 찾아내기 전까지는. ‘레오’의 권유로 축구를 시작하게 된 ‘나기’는 압도적인 축구 센스를 발휘하고 어느 날, 그들에게 ‘블루 록’ 프로젝트 초대장이 도착한다. 그곳에서 ‘이사기 요이치’, ‘바치라 메구루’, ‘이토시 린’ 등, 전국에서 선별된 스트라이커들이 기다리고 있는데…",
      popularity: 174.525,
      poster_path: "/yN773yRQjwG6KPjUGqBsmiLfKom.jpg",
      release_date: "2024-08-21",
      title: "극장판 블루 록 -에피소드 나기-",
      video: false,
      vote_average: 7.244,
      vote_count: 45,
    },
    {
      adult: false,
      backdrop_path: "/vvIKttfL7SoE9rZyLkg6TaAVsDH.jpg",
      genre_ids: [27, 53],
      id: 1010600,
      original_language: "en",
      original_title: "The Strangers: Chapter 1",
      overview:
        "외딴집 하나, 연인 둘, 그리고 \"똑.똑.똑. 주문하신 살인마 셋 도착했습니다\"  8km 반경 아무도 없는 숲속 외딴집에서 하룻밤을 보내게 된 연인 '마야'와 '라이언'. 전기도 전화도 끊긴 섬뜩한 어둠 속에서 누군가 똑.똑.똑… 문을 두드린다.  '철컥' 문을 여는 순간, 기괴한 마스크를 쓴 살인마 크루의 사냥감이 되어버린 그들은 누구의 도움도 바랄 수 없는 최악의 상황에 갇히고... 동기도 자비도 없는, 인간사냥에 미친 세 명의 살인마에게서 탈출해야만 한다!",
      popularity: 154.894,
      poster_path: "/yVVTEtxiweNs9ZMTazWyEB2SxSL.jpg",
      release_date: "2024-08-28",
      title: "스트레인저스: 챕터1",
      video: false,
      vote_average: 5.9,
      vote_count: 321,
    },
    {
      adult: false,
      backdrop_path: "/mwdt9HsCddye6xzNvccPenaenjW.jpg",
      genre_ids: [16, 18, 35, 878],
      id: 838240,
      original_language: "es",
      original_title: "Robot Dreams",
      overview:
        "뉴욕 맨해튼에서 홀로 외롭게 살던 ‘도그’는 TV를 보다 홀린 듯 반려 로봇을 주문하고 그와 둘도 없는 단짝이 되어 행복한 나날을 보낸다. 그러던 어느 날, 해수욕장에 놀러간 ‘도그’와 ‘로봇’은 예기치 못한 상황에 휩쓸려 이별을 맞이하게 되는데···",
      popularity: 76.922,
      poster_path: "/3TfgJPOx7lzuopbXimsvYGq4vn6.jpg",
      release_date: "2024-03-13",
      title: "로봇 드림",
      video: false,
      vote_average: 8.1,
      vote_count: 478,
    },
    {
      adult: false,
      backdrop_path: "/kwGvFyRtGSSm8AFfnRNXoZTQmJj.jpg",
      genre_ids: [80, 18],
      id: 1008409,
      original_language: "en",
      original_title: "The Bikeriders",
      overview:
        "1960년대 미국이 격변하던 시절, ‘캐시’(조디 코머)는 우연히 바에서 만난 중서부 오토바이 클럽 반달스의 신입 멤버인 ‘베니’(오스틴 버틀러)에게 끌리게 된다. 이 클럽은 정체불명의 리더 ‘조니’(톰 하디)가 이끌고 있으며, 클럽이 진화해가며 각 지역 아웃사이더들이 모이는 장소의 위험한 폭력 범죄 조직으로 변해간다. 이로 인해 ‘베니’는 ‘캐시’와 클럽에 대한 충성심 사이, 선택의 기로에 놓이게 되는데...",
      popularity: 75.388,
      poster_path: "/n6RfhGJBBqeVrxOA67r65TECQXQ.jpg",
      release_date: "2024-09-25",
      title: "바이크 라이더스",
      video: false,
      vote_average: 6.869,
      vote_count: 546,
    },
    {
      adult: false,
      backdrop_path: "/TGsfNWkASegCfAn6ED1b08a9O6.jpg",
      genre_ids: [27, 9648, 53],
      id: 1125311,
      original_language: "en",
      original_title: "Imaginary",
      overview:
        "새로 이사한 집 지하실에서 우연히 곰인형을 발견한 '앨리스'는 '천시'라는 이름을 지어주고 영혼의 단짝이 된다. '천시'에게 과몰입한 ‘앨리스'는 의문의 게임 리스트에 따라 이상 행동을 하기 시작하고 결국 집 한쪽 깊숙이 숨겨져 있던 파란 문을 열게 되는데…!",
      popularity: 69.775,
      poster_path: "/gwk23mfvbNzh0zqygZChXlqHbnq.jpg",
      release_date: "2024-08-28",
      title: "이매지너리",
      video: false,
      vote_average: 6.078,
      vote_count: 438,
    },
    {
      adult: false,
      backdrop_path: "/hd95kH9RgN3W78UaFU6Sdpy9Mfl.jpg",
      genre_ids: [28, 53],
      id: 1027073,
      original_language: "en",
      original_title: "In the Land of Saints and Sinners",
      overview:
        "과거를 묻고 은퇴하는 베테랑 청부살인업자. 테러리스트들이 그의 마을에 들이닥친다. 게다가 어린 소녀를 학대하는데… 지킬 것이 생겼다. 정체가 탄로났다. 처음으로 남을 위해 다시 총을 드는데…  그의 분노가 폭발한다!",
      popularity: 38.41,
      poster_path: "/nF55Arb7cbBJQZmE3mxLEEFkM3F.jpg",
      release_date: "2024-09-04",
      title: "원맨",
      video: false,
      vote_average: 6.594,
      vote_count: 334,
    },
    {
      adult: false,
      backdrop_path: "/tWQfn3VFLyWt34JywyOFYT6OLHJ.jpg",
      genre_ids: [99, 10402],
      id: 1315707,
      original_language: "ko",
      original_title: "정국: 아이 엠 스틸",
      overview:
        "‘21세기 팝 아티스트' 방탄소년단의 정국, 그가 2023년 7월, 첫 솔로 싱글 ‘Seven(feat. Latto)’을 발표하며 ‘글로벌 팝스타'로 거듭났다. Seven, 3D, Standing Next to You를 연달아 히트시키며 2020년대를 대표하는 남성 솔로 가수로 자리매김한 정국. ‘K-팝 솔로 최초’, ‘유일무이’ 등 각종 수식어가 따라오는 정국이지만 아미(ARMY)에게 부끄럽지 않은 자랑스러운 아티스트가 되기 위해 끊임없이 노력하고 성장한다. 타고난 재능, 그 속의 빛나는 노력으로 자신만의 길을 나아가는 아티스트 정국. 그의 첫 솔로 싱글부터 GOLDEN 앨범 활동기까지 뉴욕, 런던, 서울 등 세계 각지를 누비며 진행된 약 8개월간의 ‘황금빛 순간’. 그간 보지 못했던 미공개 인터뷰와 비하인드, 그리고 전 세계 224개 국가/지역의 팬들과 온오프라인에서 함께했던 ‘Jung Kook ‘GOLDEN’ Live On Stage’ 그날의 현장으로! 여전히 하고 싶은 것도, 보여줄 것도 많은 정국의 이야기",
      popularity: 41.174,
      poster_path: "/9QPZAKSod1Fmie6qtQQqqzWGuJT.jpg",
      release_date: "2024-09-18",
      title: "정국: 아이 엠 스틸",
      video: false,
      vote_average: 9.5,
      vote_count: 1,
    },
    {
      adult: false,
      backdrop_path: "/u937kWuQPW1fTXdz50PDLasUI2e.jpg",
      genre_ids: [16, 10749],
      id: 1230477,
      original_language: "ja",
      original_title: "映画 ギヴン 柊mix",
      overview:
        "“음악에 모든 걸 걸어야 하나… 무서운 걸” 밴드 '기븐'에게 찾아온 데뷔의 기회! 리츠카는 마후유에게 함께하자고 제안하지만, 마후유는 뜻밖에 대답을 보류한다. “너와 해보고 싶은 게 있어” 밴드 'shy'의 히이라기는 리츠카에게 기타 서포트를 요청한다. 어떤 특별한 부탁과 함께. “너도 유키를 좋아했던 거지?” 마후유의 방황이 자기 탓이라고 고민하는 히이라기에게 시즈스미는 마음 속에 담아둔 말을 꺼낸다.",
      popularity: 28.654,
      poster_path: "/vsGOwmvUad2sffC3xvm8gMcSLQ5.jpg",
      release_date: "2024-08-28",
      title: "극장판 : 기븐_히이라기 믹스",
      video: false,
      vote_average: 0,
      vote_count: 0,
    },
    {
      adult: false,
      backdrop_path: "/2okfik8YwzSfdETpT5cUClSiGFO.jpg",
      genre_ids: [16, 18],
      id: 1244492,
      original_language: "ja",
      original_title: "ルックバック",
      overview:
        "4학년인 '후지노'는 학교 신문에 네컷 만화를 그리며 친구들의 극찬을 받는다. 그림에 대한 자신감으로 만화가를 꿈꾸던 ‘후지노’는 학교에 나오지 않는 동급생 ‘쿄모토’와 함께 네컷 만화를 연재하며 그림을 향한 한결 같은 마음으로 눈부신 우정을 쌓아 간다. 그러던 어느 날, 단 하나의 사건이 그들을 찾아 오는데... 만화만이 세상이 전부였던 두 소녀의 가슴 벅찬 성장 이야기가 시작된다!",
      popularity: 37.051,
      poster_path: "/ehl2Du38qbg9M2cqfoVPUKgVDTy.jpg",
      release_date: "2024-09-05",
      title: "룩백",
      video: false,
      vote_average: 8.625,
      vote_count: 12,
    },
    {
      adult: false,
      backdrop_path: "/FzntbxhtPGp5gVmie16ry3k7Ow.jpg",
      genre_ids: [16, 35, 10751, 14],
      id: 567811,
      original_language: "en",
      original_title: "10 Lives",
      overview:
        "9번째 냥생을 살고 있는 거만한 고양이 ‘베킷’은  완벽한 집사 ‘로즈’의 사랑 덕분에 더할 나위 없이 행복한 냥생을 보내던 중  어이없는 사고로 마지막 목숨을 잃게 된다.  천국의 천사에게 원래의 삶으로 되돌아가게 해달라고  간절하게 빌어 다시 한번 목숨을 얻게 되지만 조건이 하나 있었는데?!  고양이가 아닌 엉뚱한 동물로 환생하게 되는 ‘베킷’은  과연 ‘로즈’의 품으로 다시 돌아갈 수 있을까?!",
      popularity: 50.002,
      poster_path: "/m4WQh0iMxTnMbsI31GPUcAlzSxO.jpg",
      release_date: "2024-08-15",
      title: "10 라이브즈",
      video: false,
      vote_average: 8.426,
      vote_count: 88,
    },
    {
      adult: false,
      backdrop_path: "/6VoxDupaW2VXfLtJyeOoGCgXSjD.jpg",
      genre_ids: [28, 53],
      id: 1116490,
      original_language: "en",
      original_title: "Cash Out",
      overview:
        "전설적인 강도단의 보스 ‘메이슨’(존 트라볼타) 실패로 끝난 작전 이후 은퇴하고 잠적했던 그가 옛 팀원들의 다급한 요청으로 은행 강도 현장에 도착한다.  하지만 현장은 곧 치밀한 작전 따윈 사라지고 예상치 못한 FBI 협상가까지 등장하며 엉망이 되어버린다.  ‘메이슨’은 이제 FBI에 맞서 팀원들을 지키고 인생 마지막 한탕을 성공시키기 위해 완벽한 플랜 B를 설계하기 시작하는데…",
      popularity: 35.057,
      poster_path: "/4r77ZO9pKgQuW1GxjMrktyY8eUP.jpg",
      release_date: "2024-09-12",
      title: "캐시 아웃",
      video: false,
      vote_average: 5.9,
      vote_count: 59,
    },
    {
      adult: false,
      backdrop_path: "/4jdduww9j5RyzO4ITRcuBFhqNN1.jpg",
      genre_ids: [18],
      id: 965150,
      original_language: "en",
      original_title: "Aftersun",
      overview:
        "평범한 10대 소녀인 소피는 그동안 자신에게 소홀했던 아버지와 단둘이 튀르키예로 여행을 떠난다. 아버지와 처음으로 둘만의 오붓한 시간을 즐기는 동안, 소피는 어떻게든 자신을 즐겁게 해주려는 아버지의 새로운 이면을 보게 되는데…",
      popularity: 43.349,
      poster_path: "/zZh6x7aHtSxsIQCewZVKEykVNtO.jpg",
      release_date: "2023-02-01",
      title: "애프터썬",
      video: false,
      vote_average: 7.678,
      vote_count: 1327,
    },
  ],
  total_pages: 5,
  total_results: 93,
};
